/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package treehouse.haystack.io;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int NULL = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int LBRACKET = 11;
  /** RegularExpression Id. */
  int RBRACKET = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int EXP = 16;
  /** RegularExpression Id. */
  int INTEGER = 17;
  /** RegularExpression Id. */
  int FLOAT = 18;
  /** RegularExpression Id. */
  int TZ = 19;
  /** RegularExpression Id. */
  int DATE_TIME = 20;
  /** RegularExpression Id. */
  int DATE = 21;
  /** RegularExpression Id. */
  int TIME = 22;
  /** RegularExpression Id. */
  int HEX = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int ARROW = 25;
  /** RegularExpression Id. */
  int LPAREN = 26;
  /** RegularExpression Id. */
  int RPAREN = 27;
  /** RegularExpression Id. */
  int EQ = 28;
  /** RegularExpression Id. */
  int NE = 29;
  /** RegularExpression Id. */
  int LT = 30;
  /** RegularExpression Id. */
  int LE = 31;
  /** RegularExpression Id. */
  int GT = 32;
  /** RegularExpression Id. */
  int GE = 33;
  /** RegularExpression Id. */
  int HAS = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int TAG = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "<DIGIT>",
    "<EXP>",
    "<INTEGER>",
    "<FLOAT>",
    "<TZ>",
    "<DATE_TIME>",
    "<DATE>",
    "<TIME>",
    "<HEX>",
    "<STRING>",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"has\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "<TAG>",
  };

}
